version: "3.8"

services:
    mysql:
        image: mysql:latest
        container_name: mysql_container
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: auroraIgloos
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin_container
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql_container
            PMA_PORT: 3306
volumes:
    - ./docker/mysql/init:/docker-entrypoint-initdb.d
